name: app
description: Personal Finance App
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  minister_shared:
    path: ../shared
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  http: ^1.2.0
  fl_chart: ^0.70.2
  intl: ^0.19.0
  url_launcher: ^6.3.1
  file_picker: ^8.1.6
  google_fonts: ^8.0.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^4.0.0
  webview_flutter_wkwebview: ^3.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
