name: finance_server
description: Personal finance Dart server
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  minister_shared:
    path: ../shared
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  http: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
